# -------------------------------
# Stage 1: Build the React app
# -------------------------------
FROM node:20-alpine AS build

WORKDIR /app

# Copy dependency files first for better layer caching
COPY package.json package-lock.json ./

# Install exact versions from package-lock.json
# Dev dependencies are required to run Vite/build tools
RUN npm ci

# Copy source code
COPY . .

# Create production static files in /app/dist
RUN npm run build


# -------------------------------
# Stage 2: Serve with non-root Nginx, nginx unprivileged imaage is configure with a non-root user so its safe to run container without creating a user
# -------------------------------
FROM nginxinc/nginx-unprivileged:stable-alpine AS runtime

# Copy the compiled frontend only
COPY --from=build /app/dist /usr/share/nginx/html

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Unprivileged Nginx uses port 8080
EXPOSE 8080

# The image already runs as a non-root user
CMD ["nginx", "-g", "daemon off;"]