#stage 1 build stage
FROM node:20-alpine AS build
#working directory
WORKDIR /app
#copy package.json and package-lock.json
COPY package*.json /app/
#install dependencies
RUN npm ci
#copy source code
COPY . .
#build the application
RUN npm run build

#stage 2 runtime stage
FROM nginx:alpine AS runtime
WORKDIR /usr/share/nginx/html
COPY  --from=build /app/dist/ /usr/share/nginx/html/
COPY nginx.config /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
