#stage 1 build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json /app/
RUN npm ci
COPY . .
RUN npm run build

#stage 2 runtime stage
FROM nginx:alpine AS runtime
WORKDIR /usr/share/nginx/html
COPY  --from=build /app/dist/ /usr/share/nginx/html/
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
