services:
  db:
    image: postgres:15
    container_name: phonestore_db
    environment:
      POSTGRES_USER: phonestore_admin
      POSTGRES_PASSWORD: phonestore_password
      POSTGRES_DB: phonestore_db
    volumes:
      - phonestore_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phonestore_admin -d phonestore_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: ogshabzy23101/phone-store-backend:${IMAGE_TAG}
    container_name: phonestore_backend
    environment:
      PORT: "5000"
      DATABASE_URL: postgres://phonestore_admin:phonestore_password@db:5432/phonestore_db
    depends_on:
        db:
          condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:5000/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped 

  frontend:
    image: ogshabzy23101/phone-store-frontend:${IMAGE_TAG}
    container_name: phonestore_frontend
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  phonestore_db_data:
