services:
  db:
    image: postgres:15
    container_name: phonestore_db
    environment:
      POSTGRES_USER: phonestore_admin
      POSTGRES_PASSWORD: phonestore_password
      POSTGRES_DB: phonestore_db
    volumes:
      - phonestore_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phonestore_admin -d phonestore_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ../../backend
    container_name: phonestore_backend
    environment:
      PORT: "5000"
      DATABASE_URL: postgres://phonestore_admin:phonestore_password@db:5432/phonestore_db
    depends_on:
         db:
          condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    container_name: phonestore_frontend
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ../../frontend:/app
      - /app/node_modules

volumes:
  phonestore_db_data:

networks:
  default:
    name: phonestore_network
