apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  labels:
    app: {{ .Values.backend.appLabel }}
spec:
  selector:
    app: {{ .Values.backend.appLabel }}
  ports:
    - name: http
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
  type: ClusterIP