- name: Deploy Docker Compose
  hosts: web
  become: true
  tasks:
    - name: ensure app directory exists
      file:
        path: /home/ubuntu/web
        state: directory
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0755'

    - name: copy docker-compose file
      copy:
        src: ../../docker/docker-compose.prod.yml
        dest: /home/ubuntu/web
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'

    - name: validate docker-compose file
      command: docker compose -f /home/ubuntu/web/docker-compose.prod.yml config
      register: compose_config
      failed_when: compose_config.rc != 0

    - name: pull latest images
      command: docker compose -f /home/ubuntu/web/docker-compose.prod.yml pull
      args:
        chdir: /home/ubuntu/web/

    - name: run docker-compose
      command: docker compose -f docker-compose.prod.yml up -d
      args:
        chdir: /home/ubuntu/web/ 